### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [sebastiangraz/g#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by sebastiangraz** [comment]
Hi I had to change the repo and plugin name from g > c because it would interfere with certain git aliases. I added a license, but just letting you know that my plugin is exactly the same as: https://github.com/robertzk/send.zsh but the difference is with a shorter name. If you are okay with having almost duplicate plugins on the list. Cheers

**Comment by unixorn** [comment]
Duplicate functionality is fine.
